import Head from "next/head"
import Features from "@/components/features/Features"
import Teams from "@/components/teams/Teams"
import TimeLine from "@/components/timeline/Timeline"
import PrimaryFeatures from "@/components/primaryFeatures/PrimaryFeatures"

const Home = () => {
  return (
    <div>
      <Head>
        <title>GasLockR - The First Trustless GasFi Protocol </title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Features />
      <PrimaryFeatures />
      {/* <Teams /> */}
      <TimeLine />
    </div>
  )
}

export default Home
